use test;

CREATE UNIQUE INDEX I_NAME_LASTNAME_FIRSTNAME ON NAME_ (LAST_, FIRST_);
CREATE UNIQUE INDEX I_ROLE_NAME ON ROLE_ (NAME_);

CREATE UNIQUE INDEX I_SCENARIOCONFIGURATION_NAME ON SCENARIOCONFIGURATION (NAME_);

CREATE UNIQUE INDEX I_FLIGHTPLAN_NAME ON FLIGHTPLAN (NAME_);

CREATE UNIQUE INDEX I_AIRCRAFT_AIRCRAFTID ON AIRCRAFT (AIRCRAFTID);
CREATE UNIQUE INDEX I_AIRCRAFT_NAME ON AIRCRAFT (NAME_);
CREATE UNIQUE INDEX I_SCENARIO_SCENARIOID ON SCENARIO (SCENARIOID);

CREATE UNIQUE INDEX I_SCENARIO_NAME ON SCENARIO (NAME_);
CREATE UNIQUE INDEX I_SIMULATION_SIMULATIONID ON SIMULATION (SIMULATIONID);
CREATE UNIQUE INDEX I_SIMULATION_NAME ON SIMULATION (NAME_);

CREATE UNIQUE INDEX I_FEDERATE_NAME ON FEDERATE (NAME_);
CREATE UNIQUE INDEX I_FEM_NAME ON FEM (NAME_);
CREATE UNIQUE INDEX I_FEDERATEFEMASSOC_FEDNAME_FEMNAME ON FEDERATEFEMASSOC (FEDERATENAME, FEMNAME);

CREATE UNIQUE INDEX I_FEDERATEGRPASSOC_FEDNAME_GRPNAME ON FEDERATEGROUPASSOC (FEDERATENAME, GROUPNAME);
CREATE UNIQUE INDEX I_GROUPFEMASSOC_GRPNAME_FEMNAME ON GROUPFEMASSOC (FEMNAME, GROUPNAME);
CREATE UNIQUE INDEX I_GROUP_NAME ON GROUP_ (NAME_);

commit;
