
use test;

DROP TABLE IF EXISTS AIRCRAFT;
DROP TABLE IF EXISTS ERRORDESCRIPTION;
DROP TABLE IF EXISTS FLIGHTPLAN;

DROP TABLE IF EXISTS FLIGHTPLANAIRCRAFTASSOC;
DROP TABLE IF EXISTS HEARTBEATCONFIGURATION ;
DROP TABLE IF EXISTS MESSAGINGCONFIGURATION ;

DROP TABLE IF EXISTS NAME_ ;
DROP TABLE IF EXISTS OPENJPA_SEQUENCE_TABLE;
DROP TABLE IF EXISTS ROLE_ ;

DROP TABLE IF EXISTS SCENARIOCONFIGURATION ;
DROP TABLE IF EXISTS SIMULATIONEXECUTIONHANDLE ;
DROP TABLE IF EXISTS USER_ ;
DROP TABLE IF EXISTS USERROLEASSOC;

DROP TABLE IF EXISTS SCENARIO;
DROP TABLE IF EXISTS SCENARIOFLIGHTPLANASSOC;

DROP TABLE IF EXISTS SIMULATION;
DROP TABLE IF EXISTS SIMULATIONSCENARIOASSOC;

DROP TABLE IF EXISTS SCENARIOSIMULATIONEVENTASSOC;
DROP TABLE IF EXISTS SIMULATIONEVENTTYPE;

DROP TABLE IF EXISTS FLIGHTPLANEVENT;
DROP TABLE IF EXISTS AIRFLIGHTPOSITIONEVENT;

DROP TABLE IF EXISTS WEATHER;
DROP TABLE IF EXISTS WEATHEREVENT;
DROP TABLE IF EXISTS AIRSPACESECTORTYPE;
DROP TABLE IF EXISTS FOURDSPATIALLOCATIONTYPE;
DROP TABLE IF EXISTS SECTORTYPE;
DROP TABLE IF EXISTS WEATHEREVENT;

DROP TABLE IF EXISTS SECTOR;
DROP TABLE IF EXISTS AIRSPACECONFIG;
DROP TABLE IF EXISTS AIRSPACECONFIGSECTORASSOC;

DROP TABLE IF EXISTS GEOLOCATIONTYPE;
DROP TABLE IF EXISTS GEOSPATIALLOCATIONTYPE;
DROP TABLE IF EXISTS SECTORGEOSPATIALLOCATIONASSOC;

DROP TABLE IF EXISTS AIRPORT;
DROP TABLE IF EXISTS AIRPORTRUNWAYASSOC;
DROP TABLE IF EXISTS RUNWAY;

DROP TABLE IF EXISTS AIRPORTTAXIWAYASSOC;
DROP TABLE IF EXISTS GROUNDPOINT;
DROP TABLE IF EXISTS TAXIWAY;

DROP TABLE IF EXISTS PARKINGSPOT;
DROP TABLE IF EXISTS SURFACEAREA;
DROP TABLE IF EXISTS DIRECTEDGEOSPATIALLOCATION;

DROP TABLE IF EXISTS ERRORDESCRIPTION;
DROP TABLE IF EXISTS RUNWAYGROUNDPOINTASSOC;

DROP TABLE IF EXISTS AIRPORTPARKINGSPOTASSOC ;
DROP TABLE IF EXISTS GEOLOCATION ;
DROP TABLE IF EXISTS GEOSPATIALLOCATION ;
DROP TABLE IF EXISTS NAVPOINTTYPE ;
DROP TABLE IF EXISTS ROUTETYPE ;

DROP TABLE IF EXISTS AIRPORTGROUNDROUTEASSOC;

DROP TABLE IF EXISTS RUNWAY;

DROP TABLE IF EXISTS AIRPORTTAXIWAYASSOC;

DROP TABLE IF EXISTS GROUNDPOINT;

DROP TABLE IF EXISTS TAXIWAY;

DROP TABLE IF EXISTS PARKINGSPOT;

DROP TABLE IF EXISTS AIRPORTSURFACEAREAASSOC;

DROP TABLE IF EXISTS FEDERATIONEXECUTIONMODEL;

DROP TABLE IF EXISTS FEDERATIONEXECUTIONMODELNAME_0;

DROP TABLE IF EXISTS AIRWAYTYPE;

DROP TABLE IF EXISTS FEDERATIONEXECUTIONMODELREQU_0;

DROP TABLE IF EXISTS FLGHTRTEFLGHTPROCASSOC;

DROP TABLE IF EXISTS FLIGHTPROCEDURE;

DROP TABLE IF EXISTS FLIGHTROUTE;

DROP TABLE IF EXISTS FLIGHTROUTENAVAIDASSOC;

DROP TABLE IF EXISTS GROUNDROUTE;

DROP TABLE IF EXISTS NAVAID;

DROP TABLE IF EXISTS USERSIMULATIONASSOC;

DROP TABLE IF EXISTS FEM;

DROP TABLE IF EXISTS ORGANIZATION;

DROP TABLE IF EXISTS USERFEMASSOC;

DROP TABLE IF EXISTS FEDERATEFEMASSOC;

DROP TABLE IF EXISTS GROUP_;

DROP TABLE IF EXISTS GROUPFEMASSOC;

DROP TABLE IF EXISTS USADDRESSTYPE;

DROP TABLE IF EXISTS USERGROUPASSOC;

DROP TABLE IF EXISTS FEDERATE;

DROP TABLE IF EXISTS USERORGASSOC;

DROP TABLE IF EXISTS FEDERATEGROUPASSOC;

DROP TABLE IF EXISTS LICENSE;

DROP TABLE IF EXISTS LICENSEORGASSOC;

DROP TABLE IF EXISTS LICENSEUSAGE;

drop table if exists PARTICIPANT;

drop table if exists AIRFLIGHTPOSITION;

drop table if exists SIMULATIONMETRICS;

drop table if exists SIMULATIONSIMMETRICSASSOC;

commit;
