use test;

DROP INDEX I_NAME_LASTNAME_FIRSTNAME ON NAME_;
DROP INDEX I_ROLE_NAME ON ROLE_;

DROP INDEX I_SCENARIOCONFIGURATION_NAME ON SCENARIOCONFIGURATION;
DROP INDEX I_FLIGHTPLAN_FLIGHTPLANID ON SCENARIOCONFIGURATION;
DROP INDEX I_FLIGHTPLAN_NAME ON SCENARIOCONFIGURATION;
DROP INDEX I_AIRCRAFT_AIRCRAFTID ON AIRCRAFT;
DROP INDEX I_AIRCRAFT_NAME ON AIRCRAFT;
DROP INDEX I_SCENARIO_SCENARIOID ON SENARIO;
DROP INDEX I_SCENARIO_NAME ON SCENARIO;

DROP INDEX I_SIMULATIONEXECUTIONINSTANCE_SIMULATIONID ON SIMULATION;
DROP INDEX I_SIMULATIONEXECUTIONINSTANCE_NAME ON SIMULATION;

DROP INDEX I_FEDERATE_NAME ON FEDERATE;
DROP INDEX I_FEM_NAME ON FEM ;
DROP INDEX I_FEDERATEFEMASSOC_FEDNAME_FEMNAME ON FEDERATEFEMASSOC;

commit;
